spring:
  profiles:
    default: local

  datasource:
    url: jdbc:mysql://localhost:3306/coffee
    driver-class-name:
    username: coffee
    password: coffee1234#$#$
  cache:
    type: redis
  hikari:
    maximum-pool-size: 100

  data:
    redis:
      host: localhost
      port: 6379

management:
  endpoint:
    health:
      show-details: always


---
spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    p6spy:
      logMessageFormat:
        p6spy: "%(currentTime)|%(executionTime)|%(category)|%(sqlSingleLine)"

  h2:
    console:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: test


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 100
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
        dialect.storage_engine: innodb
  p6spy:
    logMessageFormat:
      p6spy: "%(currentTime)|%(executionTime)|%(category)|%(sqlSingleLine)"
  sql:
    init:
      mode: never
logging:
  level:
    org.redisson: info
    com.zaxxer.hikari: debug
