spring:
  profiles:
    default: local

  datasource:
    url: jdbc:mariadb://localhost:3306/coffee
    driver-class-name: org.mariadb.jdbc.Driver
    username: coffee
    password: coffee1234#$#$
  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379

management:
  endpoint:
    health:
      show-details: always

---
spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    p6spy:
      logMessageFormat:
        p6spy: "%(currentTime)|%(executionTime)|%(category)|%(sqlSingleLine)"

  h2:
    console:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: test


  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mariadb://localhost:3306/coffee-test
    driver-class-name: org.mariadb.jdbc.Driver
    username: coffee
    password: coffee1234#$#$
    hikari:
      maximum-pool-size: 100
    p6spy:
      logMessageFormat:
        p6spy: "%(currentTime)|%(executionTime)|%(category)|%(sqlSingleLine)"
  sql:
    init:
      mode: never
logging:
  org.redisson: info
