spring:
  profiles:
    default: local

  datasource:
    url: jdbc:mariadb://localhost:3306/coffee
    driver-class-name: org.mariadb.jdbc.Driver
    username: coffee
    password: coffee1234#$#$
  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379

management:
  endpoint:
    health:
      show-details: always


---
spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    p6spy:
      logMessageFormat:
        p6spy: "%(currentTime)|%(executionTime)|%(category)|%(sqlSingleLine)"

  h2:
    console:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: test


  jpa:
  datasource:
    url: jdbc:h2:mem:test_db;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
    database: h2
    generate-ddl: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
        dialect.storage_engine: innodb

    hikari:
      maximum-pool-size: 100
    p6spy:
      logMessageFormat:
        p6spy: "%(currentTime)|%(executionTime)|%(category)|%(sqlSingleLine)"
  sql:
    init:
      mode: never
logging:
  level:
    org.redisson: info
    com.zaxxer.hikari: debug
